theme: jekyll-theme-dinky

{
    "api_url": "https://api.github.com",
    "environment": "dotcom",
    "project_title": "Clan-Kriminalit채t",
    "project_tagline": "Die lange Tradition der Einzelf채lle in CDU und CSU.",
    "owner_url": "https://github.com/clerosieu",
    "repository_url": "https://github.com/clerosieu/clerosieu.github.io/",
    "repository_name": "Clan-Kriminalit채t",
    "url": "https://www.clan-kriminalit채t.de/", // (or the CNAME)
}
